// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/events": {
            "get": {
                "description": "公開イベントを指定ソート順で返す。認証不要。\nsort は \"created_at\"(デフォルト) / \"event_date\" のみ許可。不正値はデフォルトに戻す。\norder は \"desc\"(デフォルト) / \"asc\" のみ許可。不正値はデフォルトに戻す。\nprifileはProfileSummaryを返す。\nq は検索キーワード。反復指定で AND 検索になる（例: ?q=桜\u0026q=東京）。各語はタイトル/イベント詳細/\n主催者名/地域名/持ち物を横断して部分一致で判定し、全語に一致するイベントを返す。未指定なら全件（最大10語）。\n照合は大文字小文字を無視し、半角/全角も同一視する（NFKC正規化。全角数字↔半角数字・全角英字↔半角英字・半角カナ↔全角カナ）。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "event"
                ],
                "summary": "イベント一覧取得",
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "検索キーワード(反復指定でAND検索。各語を5項目横断・部分一致・大小無視。最大10件)",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "ソートカラム(created_at|event_date, default: created_at)",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "ソート順(asc|desc, default: desc)",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "取得件数(default 20, 最大 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "取得開始位置(default 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.EventListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.InternalErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "認証済みユーザーが新規イベントを投稿する。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "event"
                ],
                "summary": "イベント投稿",
                "parameters": [
                    {
                        "description": "イベント投稿リクエスト",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.CreateEventRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.CreateEventResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ValidationErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.UnauthorizedErrorResponse"
                        }
                    },
                    "413": {
                        "description": "Request Entity Too Large",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.RequestTooLargeErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.InternalErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/events/{id}": {
            "get": {
                "description": "指定されたイベントIDの詳細情報を取得する。cancelledAt が null 以外の場合は開催取りやめ。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "event"
                ],
                "summary": "イベント詳細取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "イベントID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.EventResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.NotFoundErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.InternalErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/events/{id}/cancel": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "イベント主催者がイベントを開催取りやめにする。主催者のみ実行可能。\n非冪等: 参加者へ送る通知メールの件名・本文を必須で受け取り、\nキャンセル確定と同一トランザクションで通知を outbox に予約する\n（バックグラウンドワーカーが個別送信する）。既にキャンセル済みの\nイベントに対する呼び出しは 409 を返す。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "event"
                ],
                "summary": "イベントの取りやめ（キャンセル）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "イベントID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "キャンセル通知リクエスト",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.CancelEventRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.CancelEventResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ValidationErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.UnauthorizedErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ForbiddenErrorResponse"
                        }
                    },
                    "409": {
                        "description": "already_cancelled: このイベントは既にキャンセルされています",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ConflictErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.InternalErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/events/{id}/join": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "認証は任意。ログイン時のみ profileId が記録される。\nAuthorization ヘッダなし → 匿名参加（profileId = null）。\nヘッダありでトークンが無効 → 401 で中断。\nヘッダありで有効 → profileId を記録してログイン参加。\npartySizeで代表者を含む参加人数を指定できる。\nイベント定員を超える場合は409 Conflict（capacity_full）を返す。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "event"
                ],
                "summary": "イベント参加",
                "parameters": [
                    {
                        "type": "string",
                        "description": "イベントID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "参加申込",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.JoinEventRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.JoinEventResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ValidationErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.UnauthorizedErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.NotFoundErrorResponse"
                        }
                    },
                    "409": {
                        "description": "already_joined: 既に参加しています / capacity_full: 定員に達しています",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.JoinConflictErrorResponse"
                        }
                    },
                    "413": {
                        "description": "Request Entity Too Large",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.RequestTooLargeErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.RateLimitedErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.InternalErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/events/{id}/leave": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "認証必須。ログイン参加者が自身の参加を取り消す。\n参加行を削除し、参加状態ログへ action=leave を1件追記する。\n匿名参加（profileId=null）は本 API の対象外。\nそのイベントに参加していない場合は 404 not_found を返す。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "event"
                ],
                "summary": "イベント参加キャンセル",
                "parameters": [
                    {
                        "type": "string",
                        "description": "イベントID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.LeaveEventResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ValidationErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.UnauthorizedErrorResponse"
                        }
                    },
                    "404": {
                        "description": "not_found: イベント不存在 または 未参加",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.NotFoundErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.InternalErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/events/{id}/members": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "イベント主催者が、参加者一覧を取得する。主催者のみ閲覧可能。\nprofileId は匿名参加（ログインしていない）の場合 null。\nイベント不存在は 400 invalid_request（兄弟エンドポイントと統一）。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "event"
                ],
                "summary": "イベント参加者一覧取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "イベントID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.EventMemberListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ValidationErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.UnauthorizedErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ForbiddenErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.InternalErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/events/{id}/notifications": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "イベント主催者が、参加者全員へ運用通知メールを一斉送信する。送信できるのはイベント主催者のみ。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notification"
                ],
                "summary": "イベント参加者への一斉送信",
                "parameters": [
                    {
                        "type": "string",
                        "description": "イベントID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "一斉送信リクエスト",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.SendEventNotificationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.SendEventNotificationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ValidationErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.UnauthorizedErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ForbiddenErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.RateLimitedErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.InternalErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/events/{id}/participation-logs": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "認証ユーザー自身の、指定イベントに対する最新の参加状態を取得する。\n申し込もうとしているユーザーが既に参加しているかを判定するために使う。\n履歴が1件もない場合は action=null, participating=false, updatedAt=null を返す（200）。\n主催者権限は不要。本人の参加状態のみを返す。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "event"
                ],
                "summary": "イベント参加状態取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "イベントID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ParticipationStatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ValidationErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.UnauthorizedErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.NotFoundErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.InternalErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "イベント参加/キャンセルは別APIへ移行したため、本エンドポイントは現在無効。\n呼び出すと 410 Gone を返す。実装はサーバ内に温存しており、将来再有効化する可能性がある。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "event"
                ],
                "summary": "イベント参加状態ログ追加（廃止予定・現在無効）",
                "deprecated": true,
                "parameters": [
                    {
                        "type": "string",
                        "description": "イベントID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "参加状態",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.CreateParticipationLogRequest"
                        }
                    }
                ],
                "responses": {
                    "410": {
                        "description": "Gone",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.GoneErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/events/{id}/report": {
            "get": {
                "description": "指定したイベントIDに紐づくレポートを取得する。1イベント1レポート。認証不要。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "report"
                ],
                "summary": "レポート取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "イベントID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ReportResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.NotFoundErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.InternalErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "認証済みユーザー自身のプロフィールを返す(初回アクセス時に自動作成)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "本人プロフィール取得",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ProfileResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.UnauthorizedErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.InternalErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "認証済みユーザー自身のプロフィールを更新する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "本人プロフィール更新",
                "parameters": [
                    {
                        "description": "更新内容",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.UpdateProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ProfileResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ValidationErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.UnauthorizedErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.NotFoundErrorResponse"
                        }
                    },
                    "413": {
                        "description": "Request Entity Too Large",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.RequestTooLargeErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.InternalErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/profiles/{id}": {
            "get": {
                "description": "指定したユーザー ID のプロフィールを返す",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "ユーザープロフィール取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ユーザー ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ProfilePublic"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.NotFoundErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.InternalErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/reports": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "認証済みユーザーがイベントに対してレポートを投稿する。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "report"
                ],
                "summary": "レポート投稿",
                "parameters": [
                    {
                        "description": "レポート投稿リクエスト",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.CreateReportRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.CreateReportResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ValidationErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.UnauthorizedErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ForbiddenErrorResponse"
                        }
                    },
                    "413": {
                        "description": "Request Entity Too Large",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.RequestTooLargeErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.InternalErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/tags": {
            "get": {
                "description": "タグ一覧を取得する。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tag"
                ],
                "summary": "タグ一覧取得",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.TagListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.InternalErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "新しいタグを登録する。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tag"
                ],
                "summary": "タグ作成",
                "parameters": [
                    {
                        "description": "タグ作成",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.CreateTagRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.TagResponse"
                        }
                    },
                    "400": {
                        "description": "入力エラー",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未認証",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.UnauthorizedErrorResponse"
                        }
                    },
                    "409": {
                        "description": "タグ重複",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.InternalErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/uploads/presign": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定した kind/contentType に対応する R2 tmp 領域への PUT 署名付き URL を返す。\n返却された uploadUrl に直接 PUT することでクライアントがファイルをアップロードできる。\n取得した objectKey をイベント作成時の imageObjectKeys/pdfObjectKeys に渡すこと。\nkind=\"image\": image/jpeg, image/png のみ対応（WebP は MVP 非対応）。\nkind=\"pdf\": application/pdf のみ対応。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "upload"
                ],
                "summary": "アップロード用署名付き URL 発行",
                "parameters": [
                    {
                        "description": "presign リクエスト",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.PresignRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.PresignResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ValidationErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.UnauthorizedErrorResponse"
                        }
                    },
                    "413": {
                        "description": "Request Entity Too Large",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.RequestTooLargeErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.InternalErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "サーバーが正常に稼働しているか確認する",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "ヘルスチェック",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.HealthResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.CancelEventRequest": {
            "description": "イベント取りやめ確定時に参加者へ送る通知の件名・本文。同一トランザクションで outbox に予約され、バックグラウンドワーカーが参加者へ個別送信する。",
            "type": "object",
            "required": [
                "body",
                "subject"
            ],
            "properties": {
                "body": {
                    "description": "Body は参加者へ送る通知メールの本文（必須・10,000文字以内）。",
                    "type": "string",
                    "maxLength": 10000,
                    "example": "台風接近に伴い、安全のため本イベントは中止とさせていただきます。"
                },
                "subject": {
                    "description": "Subject は参加者へ送る通知メールの件名（必須・255文字以内）。",
                    "type": "string",
                    "maxLength": 255,
                    "example": "【重要】イベント開催中止のお知らせ"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.CancelEventResponse": {
            "type": "object",
            "properties": {
                "cancelledAt": {
                    "description": "CancelledAt はキャンセル日時(RFC3339)。",
                    "type": "string",
                    "example": "2026-06-25T10:00:00Z"
                },
                "id": {
                    "description": "ID はキャンセルしたイベントの UUID。",
                    "type": "string",
                    "example": "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ConflictErrorBody": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Code は機械可読なエラーコード。",
                    "type": "string",
                    "example": "conflict"
                },
                "message": {
                    "description": "Message は人間向けのエラーメッセージ。",
                    "type": "string",
                    "example": "既に参加しています"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ConflictErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ConflictErrorBody"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.CreateEventRequest": {
            "description": "イベント投稿に必要な情報。",
            "type": "object",
            "required": [
                "costs",
                "description",
                "eventDate",
                "location",
                "title"
            ],
            "properties": {
                "capacity": {
                    "description": "Capacity は定員（任意・0=未設定・正数=定員）。",
                    "type": "integer",
                    "minimum": 0,
                    "example": 30
                },
                "costs": {
                    "description": "Costs は費用内訳（1件以上必須）。",
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.EventCostInput"
                    }
                },
                "description": {
                    "description": "Description はイベント説明（必須・10,000文字以内）。",
                    "type": "string",
                    "maxLength": 10000,
                    "example": "春の桜を観察するイベントです。"
                },
                "eventDate": {
                    "description": "EventDate はイベント開催日時(RFC3339)（必須）。",
                    "type": "string",
                    "example": "2026-07-01T10:00:00Z"
                },
                "externalUrl": {
                    "description": "ExternalURL は関連URLs（任意・255文字以内・http/https）。",
                    "type": "string",
                    "maxLength": 255,
                    "example": "https://example.com/event"
                },
                "imageFilenames": {
                    "description": "ImageFilenames は画像の元ファイル名一覧（任意）。指定時は ImageObjectKeys と同数・同順。\nダウンロード時のファイル名（Content-Disposition）と UI 表示に使う。",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "imageObjectKeys": {
                    "description": "ImageObjectKeys は画像オブジェクトキーの一覧（任意）。",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "items": {
                    "description": "Items は持ち物リスト（任意）。",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.EventItemInput"
                    }
                },
                "location": {
                    "description": "Location は開催場所（必須・255文字以内）。",
                    "type": "string",
                    "maxLength": 255,
                    "example": "東京都新宿御苑"
                },
                "pdfFilenames": {
                    "description": "PdfFilenames はPDFの元ファイル名一覧（任意）。指定時は PdfObjectKeys と同数・同順。",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "pdfObjectKeys": {
                    "description": "PdfObjectKeys はPDFオブジェクトキーの一覧（任意・各要素255文字以内）。",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "tagIds": {
                    "description": "TagIDs は紐づけるタグの UUID 一覧（任意）。",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
                    ]
                },
                "title": {
                    "description": "Title はイベントタイトル（必須・255文字以内）。",
                    "type": "string",
                    "maxLength": 255,
                    "example": "サクラ観察会"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.CreateEventResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "CreatedAt はレコード作成日時(RFC3339)。",
                    "type": "string",
                    "example": "2026-06-23T12:00:00Z"
                },
                "id": {
                    "description": "ID は生成されたイベントの UUID。",
                    "type": "string",
                    "example": "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.CreateParticipationLogRequest": {
            "description": "イベント参加状態ログ追加に必要な情報。認証必須。",
            "type": "object",
            "required": [
                "action"
            ],
            "properties": {
                "action": {
                    "description": "Action は参加状態（必須・join または leave）。",
                    "type": "string",
                    "enum": [
                        "join",
                        "leave"
                    ],
                    "example": "join"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.CreateReportRequest": {
            "description": "レポート投稿に必要な情報。",
            "type": "object",
            "required": [
                "content",
                "eventId"
            ],
            "properties": {
                "content": {
                    "description": "Content はレポート内容（必須・10,000文字以内）。",
                    "type": "string",
                    "maxLength": 10000,
                    "example": "多摩川アメリカザリガニ殲滅作戦の結果、参加者：5人、アメリカザリガニ防除数：138匹でした。"
                },
                "eventId": {
                    "description": "EventID はレポート対象のイベントID（必須・255文字以内）。",
                    "type": "string",
                    "maxLength": 255,
                    "example": "event_1234567890"
                },
                "externalUrls": {
                    "description": "ExternalUrls は外部レポートの参照URL一覧（任意・各要素2048文字以内・http/https のみ）。",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "imageFilenames": {
                    "description": "ImageFilenames は画像の元ファイル名一覧（任意）。指定時は ImageObjectKeys と同数・同順。",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "imageObjectKeys": {
                    "description": "ImageObjectKeys は画像オブジェクトキーの一覧（任意）。",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "pdfFilenames": {
                    "description": "PdfFilenames はPDFの元ファイル名一覧（任意）。指定時は PdfObjectKeys と同数・同順。",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "pdfObjectKeys": {
                    "description": "PdfObjectKeys はPDFオブジェクトキーの一覧（任意・各要素255文字以内）。",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.CreateReportResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "CreatedAt はレコード作成日時(RFC3339)。DB の TIMESTAMPTZ を UTC で保持する。",
                    "type": "string",
                    "example": "2026-06-26T03:08:24Z"
                },
                "reportId": {
                    "description": "ReportID は作成されたレポートのID。",
                    "type": "string",
                    "example": "report_1234567890"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.CreateTagRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "description": "Name はタグ名。",
                    "type": "string",
                    "maxLength": 30,
                    "example": "外来生物"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ErrorBody": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Code は機械可読なエラーコード。",
                    "type": "string",
                    "example": "internal_error"
                },
                "message": {
                    "description": "Message は人間向けのエラーメッセージ。",
                    "type": "string",
                    "example": "サーバー内部でエラーが発生しました"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ErrorBody"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.EventCostInput": {
            "type": "object",
            "required": [
                "category"
            ],
            "properties": {
                "category": {
                    "description": "Category は費用カテゴリ（例: \"参加費\"）。",
                    "type": "string",
                    "maxLength": 255
                },
                "cost": {
                    "description": "Cost は費用（円）。0 以上の整数。",
                    "type": "integer",
                    "minimum": 0
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.EventCostResponse": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "cost": {
                    "type": "integer"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.EventItemInput": {
            "type": "object",
            "required": [
                "item"
            ],
            "properties": {
                "isRequired": {
                    "description": "IsRequired は必須かどうか。",
                    "type": "boolean"
                },
                "item": {
                    "description": "Item は持ち物名（例: \"双眼鏡\"）。",
                    "type": "string",
                    "maxLength": 255
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.EventItemResponse": {
            "type": "object",
            "properties": {
                "isRequired": {
                    "type": "boolean"
                },
                "item": {
                    "type": "string"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.EventListResponse": {
            "type": "object",
            "properties": {
                "events": {
                    "description": "Events はイベントサマリーの一覧。",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.EventSummary"
                    }
                },
                "limit": {
                    "description": "Limit は正規化後の実際に使われた取得件数。",
                    "type": "integer",
                    "example": 20
                },
                "offset": {
                    "description": "Offset は正規化後の実際に使われた取得開始位置。",
                    "type": "integer",
                    "example": 0
                },
                "totalCount": {
                    "description": "TotalCount はフィルタなし全件数。クライアントが最終ページ offset を算出するために使う。",
                    "type": "integer",
                    "example": 153
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.EventMemberListResponse": {
            "type": "object",
            "properties": {
                "members": {
                    "description": "Members は参加者の一覧。0件の場合は空配列（null ではない）。",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.EventMemberResponse"
                    }
                },
                "totalCount": {
                    "description": "TotalCount は参加者総数（client の表示用）。",
                    "type": "integer",
                    "example": 5
                },
                "totalMembers": {
                    "description": "TotalMembers は全参加者の partySize 合計（実際の総参加人数）。",
                    "type": "integer",
                    "example": 8
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.EventMemberResponse": {
            "description": "参加者1人分の情報。profileId は匿名参加の場合 null。",
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "CreatedAt は参加申込日時(RFC3339)。",
                    "type": "string",
                    "example": "2026-07-01T12:00:00Z"
                },
                "mailAddress": {
                    "description": "MailAddress は参加者のメールアドレス。",
                    "type": "string",
                    "example": "yamada@example.com"
                },
                "partySize": {
                    "description": "PartySize は代表者を含む参加人数。",
                    "type": "integer",
                    "example": 1
                },
                "profileId": {
                    "description": "ProfileID は参加者のプロフィールUUID。匿名参加の場合は null。",
                    "type": "string",
                    "example": "b2c3d4e5-f6a7-8901-bcde-f23456789012"
                },
                "username": {
                    "description": "Username は参加者の表示名。",
                    "type": "string",
                    "example": "山田太郎"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.EventResponse": {
            "type": "object",
            "properties": {
                "cancelledAt": {
                    "description": "CancelledAt はイベントが取りやめになった日時(RFC3339)。nil の場合は開催予定。",
                    "type": "string"
                },
                "capacity": {
                    "type": "integer"
                },
                "costs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.EventCostResponse"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "eventDate": {
                    "type": "string"
                },
                "externalUrl": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "imageFilenames": {
                    "description": "ImageFilenames は ImageObjectKeys に対応する元ファイル名（未設定は空文字）。",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "imageObjectKeys": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "imageUrls": {
                    "description": "ImageUrls は ImageObjectKeys に対応する表示用の完全URL。\n公開ベースURL（R2_PUBLIC_BASE_URL）未設定時は空配列。",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.EventItemResponse"
                    }
                },
                "location": {
                    "type": "string"
                },
                "pdfFilenames": {
                    "description": "PdfFilenames は PdfObjectKeys に対応する元ファイル名（未設定は空文字）。",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "pdfObjectKeys": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "pdfUrls": {
                    "description": "PdfUrls は PdfObjectKeys に対応する表示用の完全URL。\n公開ベースURL（R2_PUBLIC_BASE_URL）未設定時は空配列。",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "profile": {
                    "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ProfileSummary"
                },
                "tags": {
                    "description": "Tags は紐づくタグの一覧（name 昇順）。",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.TagResponse"
                    }
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.EventSummary": {
            "type": "object",
            "properties": {
                "cancelledAt": {
                    "description": "CancelledAt はイベントが取りやめになった日時(RFC3339)。nil の場合は開催予定。",
                    "type": "string",
                    "example": "2026-06-25T10:00:00Z"
                },
                "createdAt": {
                    "description": "CreatedAt はレコード作成日時(RFC3339)。",
                    "type": "string",
                    "example": "2026-06-22T12:00:00Z"
                },
                "eventDate": {
                    "description": "EventDate はイベント開催日時(RFC3339)。",
                    "type": "string",
                    "example": "2026-07-01T10:00:00Z"
                },
                "id": {
                    "description": "ID はイベントの一意識別子(UUID)。",
                    "type": "string",
                    "example": "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
                },
                "location": {
                    "description": "Location は開催場所（文字列）。",
                    "type": "string",
                    "example": "東京都新宿御苑"
                },
                "profile": {
                    "description": "ProfileSummary は投稿者プロフィールのサマリー情報。",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ProfileSummary"
                        }
                    ]
                },
                "profileId": {
                    "description": "ProfileID は投稿者のプロフィール ID(UUID)。",
                    "type": "string",
                    "example": "d290f1ee-6c54-4b01-90e6-d701748f0851"
                },
                "tags": {
                    "description": "Tags は紐づくタグの一覧（name 昇順）。タグが無い場合は省略される。",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.TagResponse"
                    }
                },
                "title": {
                    "description": "Title はイベントタイトル。",
                    "type": "string",
                    "example": "サクラ観察会"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ForbiddenErrorBody": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Code は機械可読なエラーコード。",
                    "type": "string",
                    "example": "forbidden"
                },
                "message": {
                    "description": "Message は人間向けのエラーメッセージ。",
                    "type": "string",
                    "example": "このイベントにレポートを投稿する権限がありません"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ForbiddenErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ForbiddenErrorBody"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.GoneErrorBody": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Code は機械可読なエラーコード。",
                    "type": "string",
                    "example": "gone"
                },
                "message": {
                    "description": "Message は人間向けのエラーメッセージ。",
                    "type": "string",
                    "example": "このエンドポイントは現在無効です。イベント参加/キャンセルは別APIを利用してください"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.GoneErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.GoneErrorBody"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "description": "Status はサーバの稼働状態。正常時は \"ok\"。",
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.InternalErrorBody": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Code は機械可読なエラーコード。",
                    "type": "string",
                    "example": "internal_error"
                },
                "message": {
                    "description": "Message は人間向けのエラーメッセージ。",
                    "type": "string",
                    "example": "サーバー内部でエラーが発生しました"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.InternalErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.InternalErrorBody"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.JoinConflictErrorBody": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Code は競合の原因を表す機械可読なエラーコード。\nalready_joined = 既に参加済み / capacity_full = 定員到達。",
                    "type": "string",
                    "enum": [
                        "already_joined",
                        "capacity_full"
                    ],
                    "example": "already_joined"
                },
                "message": {
                    "description": "Message は人間向けのエラーメッセージ。\nalready_joined なら「既に参加しています」、capacity_full なら「定員に達しています」。",
                    "type": "string",
                    "example": "既に参加しています"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.JoinConflictErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.JoinConflictErrorBody"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.JoinEventRequest": {
            "description": "イベント参加申込に必要な情報。認証は任意。",
            "type": "object",
            "required": [
                "mailAddress",
                "partySize",
                "username"
            ],
            "properties": {
                "mailAddress": {
                    "description": "MailAddress は参加するユーザーのメールアドレス（必須）。",
                    "type": "string",
                    "maxLength": 255,
                    "example": "yamada@example.com"
                },
                "partySize": {
                    "description": "PartySize は代表者を含む参加人数（必須・1以上）。",
                    "type": "integer",
                    "minimum": 1,
                    "example": 1
                },
                "username": {
                    "description": "Username は参加するユーザーの表示名（必須・255文字以内）。",
                    "type": "string",
                    "maxLength": 255,
                    "example": "山田太郎"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.JoinEventResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "CreatedAt は参加申込日時。",
                    "type": "string",
                    "example": "2023-01-01T12:00:00Z"
                },
                "eventId": {
                    "description": "EventID は参加したイベントのUUID。",
                    "type": "string",
                    "example": "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
                },
                "mailAddress": {
                    "description": "MailAddress は参加するユーザーのメールアドレス。",
                    "type": "string",
                    "example": "yamada@example.com"
                },
                "partySize": {
                    "description": "PartySize は代表者を含む参加人数。",
                    "type": "integer",
                    "example": 1
                },
                "profileId": {
                    "description": "ProfileID は参加するユーザーのUUID。ログイン時のみ記録され、匿名参加時は null。",
                    "type": "string",
                    "example": "b2c3d4e5-f6a7-8901-bcde-f23456789012"
                },
                "username": {
                    "description": "Username は参加するユーザーの表示名。",
                    "type": "string",
                    "example": "山田太郎"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.LeaveEventResponse": {
            "description": "参加キャンセルの結果。追記された参加状態ログ（action=leave）1件分の内容を返す。",
            "type": "object",
            "properties": {
                "action": {
                    "description": "Action は参加状態ログのアクション。常に \"leave\"。",
                    "type": "string",
                    "example": "leave"
                },
                "createdAt": {
                    "description": "CreatedAt は参加状態ログ（leave）の記録日時。",
                    "type": "string",
                    "example": "2026-07-01T12:00:00Z"
                },
                "eventId": {
                    "description": "EventID はキャンセルしたイベントのUUID。",
                    "type": "string",
                    "example": "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
                },
                "profileId": {
                    "description": "ProfileID はキャンセルしたユーザーのUUID。leave は認証必須のため常に値が入る。",
                    "type": "string",
                    "example": "b2c3d4e5-f6a7-8901-bcde-f23456789012"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.NotFoundErrorBody": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Code は機械可読なエラーコード。",
                    "type": "string",
                    "example": "not_found"
                },
                "message": {
                    "description": "Message は人間向けのエラーメッセージ。",
                    "type": "string",
                    "example": "リソースが見つかりません"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.NotFoundErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.NotFoundErrorBody"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ParticipationStatusResponse": {
            "description": "認証ユーザー自身の最新の参加状態。履歴が1件もない場合は action=null, participating=false, updatedAt=null。",
            "type": "object",
            "properties": {
                "action": {
                    "description": "Action は最新の参加アクション。履歴なしの場合は null。\n\"join\" または \"leave\" のいずれか。",
                    "type": "string",
                    "x-nullable": true,
                    "example": "join"
                },
                "participating": {
                    "description": "Participating は最新アクションから派生した参加フラグ。\naction=\"join\" なら true、それ以外（leave or 履歴なし）は false。",
                    "type": "boolean",
                    "example": true
                },
                "updatedAt": {
                    "description": "UpdatedAt は最新アクションの発生日時(RFC3339)。履歴なしの場合は null。",
                    "type": "string",
                    "x-nullable": true,
                    "example": "2026-07-01T12:00:00Z"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.PresignRequest": {
            "description": "アップロード用署名付き URL の発行リクエスト。",
            "type": "object",
            "required": [
                "contentType",
                "kind"
            ],
            "properties": {
                "contentType": {
                    "description": "ContentType は MIME タイプ。\n画像: \"image/jpeg\" / \"image/png\"\nPDF: \"application/pdf\"",
                    "type": "string",
                    "example": "image/jpeg"
                },
                "kind": {
                    "description": "Kind はアップロードするファイルの種別。\"image\" または \"pdf\" のみ有効。",
                    "type": "string",
                    "enum": [
                        "image",
                        "pdf"
                    ],
                    "example": "image"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.PresignResponse": {
            "description": "アップロード用署名付き URL とオブジェクトキー。",
            "type": "object",
            "properties": {
                "expiresAt": {
                    "description": "ExpiresAt は署名付き URL の有効期限(RFC3339)。",
                    "type": "string",
                    "example": "2026-07-01T10:05:00Z"
                },
                "objectKey": {
                    "description": "ObjectKey はアップロード先のオブジェクトキー。イベント作成時に imageObjectKeys/pdfObjectKeys に渡す。",
                    "type": "string",
                    "example": "natueve/tmp/profile-uuid/uuid.jpg"
                },
                "uploadUrl": {
                    "description": "UploadURL はファイルを直接 PUT するための署名付き URL。",
                    "type": "string",
                    "example": "https://xxxxx.r2.cloudflarestorage.com/natuportal/natueve/tmp/profile-uuid/uuid.jpg?X-Amz-..."
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ProfilePublic": {
            "type": "object",
            "properties": {
                "avatarUrl": {
                    "description": "AvatarURL はアバター画像 URL(未設定なら空)。",
                    "type": "string",
                    "example": "https://example.com/avatar.png"
                },
                "description": {
                    "description": "Description は自己紹介(未設定なら空)。",
                    "type": "string",
                    "example": "イベントを楽しむのが好きです。"
                },
                "displayName": {
                    "description": "DisplayName は表示名(未設定なら空)。",
                    "type": "string",
                    "example": "なちゅいべ太郎"
                },
                "id": {
                    "description": "ID は Supabase Auth のユーザー ID(UUID)。",
                    "type": "string",
                    "example": "d290f1ee-6c54-4b01-90e6-d701748f0851"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ProfileResponse": {
            "type": "object",
            "properties": {
                "avatarUrl": {
                    "description": "AvatarURL はアバター画像 URL(未設定なら空)。",
                    "type": "string",
                    "example": "https://example.com/avatar.png"
                },
                "createdAt": {
                    "description": "CreatedAt はプロフィール作成日時(RFC3339)。",
                    "type": "string",
                    "example": "2026-06-22T12:00:00Z"
                },
                "description": {
                    "description": "Description は自己紹介(未設定なら空)。",
                    "type": "string",
                    "example": "イベントを楽しむのが好きです。"
                },
                "displayName": {
                    "description": "DisplayName は表示名(未設定なら空)。",
                    "type": "string",
                    "example": "なちゅいべ太郎"
                },
                "email": {
                    "description": "Email はユーザーのメールアドレス。",
                    "type": "string",
                    "example": "user@example.com"
                },
                "id": {
                    "description": "ID は Supabase Auth のユーザー ID(UUID)。",
                    "type": "string",
                    "example": "d290f1ee-6c54-4b01-90e6-d701748f0851"
                },
                "updatedAt": {
                    "description": "UpdatedAt はプロフィール更新日時(RFC3339)。",
                    "type": "string",
                    "example": "2026-06-22T12:00:00Z"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ProfileSummary": {
            "type": "object",
            "properties": {
                "avatarUrl": {
                    "description": "AvatarURL はアバター画像 URL(未設定なら空)。",
                    "type": "string",
                    "example": "https://example.com/avatar.png"
                },
                "displayName": {
                    "description": "DisplayName は表示名(未設定なら空)。",
                    "type": "string",
                    "example": "なちゅいべ太郎"
                },
                "id": {
                    "description": "ID は Supabase Auth のユーザー ID(UUID)。",
                    "type": "string",
                    "example": "d290f1ee-6c54-4b01-90e6-d701748f0851"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.RateLimitedErrorBody": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Code は機械可読なエラーコード。",
                    "type": "string",
                    "example": "rate_limited"
                },
                "message": {
                    "description": "Message は人間向けのエラーメッセージ。",
                    "type": "string",
                    "example": "リクエストが多すぎます。しばらくしてから再試行してください"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.RateLimitedErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.RateLimitedErrorBody"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ReportResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "Content はレポート内容。",
                    "type": "string",
                    "example": "多摩川アメリカザリガニ殲滅作戦の結果、参加者：5人、防除数：138匹でした。"
                },
                "createdAt": {
                    "description": "CreatedAt はレコード作成日時(RFC3339)。",
                    "type": "string",
                    "example": "2026-06-26T03:08:24Z"
                },
                "eventId": {
                    "description": "EventID は対象イベントのID(UUID)。",
                    "type": "string",
                    "example": "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
                },
                "externalUrls": {
                    "description": "ExternalUrls は外部レポートの参照URLの一覧。無ければ空配列。",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "description": "ID はレポートの一意識別子(UUID)。",
                    "type": "string",
                    "example": "b2c3d4e5-f6a7-8901-bcde-f23456789012"
                },
                "imageFilenames": {
                    "description": "ImageFilenames は ImageObjectKeys に対応する元ファイル名（未設定は空文字）。",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "imageObjectKeys": {
                    "description": "ImageObjectKeys は画像オブジェクトキーの一覧。",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "imageUrls": {
                    "description": "ImageUrls は ImageObjectKeys に対応する表示用の完全URL。\n公開ベースURL（R2_PUBLIC_BASE_URL）未設定時は空配列。",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "pdfFilenames": {
                    "description": "PdfFilenames は PdfObjectKeys に対応する元ファイル名（未設定は空文字）。",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "pdfObjectKeys": {
                    "description": "PdfObjectKeys は PDF オブジェクトキーの一覧。",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "pdfUrls": {
                    "description": "PdfUrls は PdfObjectKeys に対応する表示用の完全URL。\n公開ベースURL（R2_PUBLIC_BASE_URL）未設定時は空配列。",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "updatedAt": {
                    "description": "UpdatedAt はレコード更新日時(RFC3339)。",
                    "type": "string",
                    "example": "2026-06-26T03:08:24Z"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.RequestTooLargeErrorBody": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Code は機械可読なエラーコード。",
                    "type": "string",
                    "example": "request_too_large"
                },
                "message": {
                    "description": "Message は人間向けのエラーメッセージ。",
                    "type": "string",
                    "example": "リクエストボディが大きすぎます（上限1MB）"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.RequestTooLargeErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.RequestTooLargeErrorBody"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.SendEventNotificationRequest": {
            "description": "イベント参加者への一斉送信に必要な件名・本文。",
            "type": "object",
            "required": [
                "body",
                "subject"
            ],
            "properties": {
                "body": {
                    "description": "Body はメールの本文（必須・10,000文字以内）。",
                    "type": "string",
                    "maxLength": 10000,
                    "example": "明日のイベントは予報通り雨となりますが、予定通り開催します。動きやすい服装でお越しください。"
                },
                "subject": {
                    "description": "Subject はメールの件名（必須・255文字以内）。",
                    "type": "string",
                    "maxLength": 255,
                    "example": "【重要】明日のイベントは雨天決行です"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.SendEventNotificationResponse": {
            "type": "object",
            "properties": {
                "eventId": {
                    "description": "EventID は送信対象のイベントID。",
                    "type": "string",
                    "example": "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
                },
                "failedCount": {
                    "description": "FailedCount は送信に失敗した件数。",
                    "type": "integer",
                    "example": 0
                },
                "recipientCount": {
                    "description": "RecipientCount は送信対象の参加者数。",
                    "type": "integer",
                    "example": 12
                },
                "sentCount": {
                    "description": "SentCount は送信に成功した件数。",
                    "type": "integer",
                    "example": 12
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.TagListResponse": {
            "type": "object",
            "properties": {
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.TagResponse"
                    }
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.TagResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "ID はタグの一意識別子(UUID)。",
                    "type": "string",
                    "example": "b2c3d4e5-f6a7-8901-bcde-f23456789012"
                },
                "name": {
                    "description": "Name はタグ名。",
                    "type": "string",
                    "example": "外来生物"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.UnauthorizedErrorBody": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Code は機械可読なエラーコード。",
                    "type": "string",
                    "example": "unauthorized"
                },
                "message": {
                    "description": "Message は人間向けのエラーメッセージ。",
                    "type": "string",
                    "example": "認証が必要です"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.UnauthorizedErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.UnauthorizedErrorBody"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.UpdateProfileRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "description": "Description は自己紹介。指定時は255文字以内（空文字でリセット可）。",
                    "type": "string",
                    "example": "イベントを楽しむのが好きです。"
                },
                "display_name": {
                    "description": "DisplayName は表示名。指定時は空不可・255文字以内（service で検証）。",
                    "type": "string",
                    "example": "なちゅいべ太郎"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ValidationErrorBody": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Code は機械可読なエラーコード。",
                    "type": "string",
                    "example": "invalid_request"
                },
                "message": {
                    "description": "Message は人間向けのエラーメッセージ。\nJSON バインド失敗時は「リクエストボディが不正です」（全エンドポイント共通）、\nフィールド検証エラー時は「タイトルは必須です」のように原因ごとの文言が入る。",
                    "type": "string",
                    "example": "リクエストボディが不正です"
                }
            }
        },
        "github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ValidationErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_GokujyouKaisennDonnburi_NatuEve_API_internal_model.ValidationErrorBody"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Supabase Auth が発行した JWT を \"Bearer \u003ctoken\u003e\" 形式で指定する",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "NatuEve API",
	Description:      "NatuEve のバックエンド API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
